### ISSUE TITLE
Netsparker Identfy : XSS & Frame Injection (param:cmd)

### ISSUE THREAD

**Issue by omarkurt** [weaknetlabs/wpes#1]
## Cross-site Scripting

Url  : http://debianserver/VulnWebApp/wpes/wpes.php  
Parameter Name :  cmd  
Parameter Type :  POST  
Attack Pattern  

``` html
"--></style></scRipt><scRipt>netsparker(0x000696)</scRipt>
```

---
## Frame Injection

Url : http://debianserver/VulnWebApp/wpes/wpes.php  
Parameter Name :  cmd  
Parameter Type :  POST  
Attack Pattern  

``` html
<iframe src=" http://r87.com/?"></iframe>
```

**Comment by RackunSec** [comment]
I didn't build in any validation or sanitation because I never knew someone would attack their own script on a compromised server. I'll add that in asap. Thanks.

**Comment by RackunSec** [comment]
Updated to prevent XSS/Code injection by replacing the < with &amp;lt; but still allows < for commands in the shell for pipe redirects, please test again with your tool.
Thanks,

**Comment by omarkurt** [comment]
Thanks for Commits.

Ohh sorry! I missed one vuln :) Check please.

## Cross-site Scripting

Url :  http://debianserver/VulnWebApp/wpes/wpes.php  
Parameter Name:  execType  
Parameter Type :  POST  
Attack Pattern :   

``` html
'"--></style></scRipt><scRipt>netsparker(0x000078)</scRipt> 
```

**Comment by RackunSec** [comment]
Again, not sure why you'd want to hack the script once you've uploaded it to the target, but, this was also resolved with the same regular expression: https://weaknetlabs.com/images/hackingmyownhack.png This should solve many issues since it breaks an opening code bracket. Thanks,
